apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: mqttoa15g-nodejs-gitops
  description: This is GitOps manifest for mqttoa15g-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: mqttoa15g-nodejs
    janus-idp.io/tekton: mqttoa15g-nodejs
    backstage.io/kubernetes-id: mqttoa15g-nodejs 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:mqttoa15g-nodejs
